Add support for thre test types for pbench-moongen

diff --git a/agent/bench-scripts/pbench-moongen b/agent/bench-scripts/pbench-moongen
--- a/agent/bench-scripts/pbench-moongen
+++ b/agent/bench-scripts/pbench-moongen
@@ -47,6 +47,7 @@ nr_flows="1024"
 nr_samples=5
 maxstddevpct=5 # maximum allowable standard deviation in percent
 max_failures=6 # after N failed attempts to hit below $maxstddevpct, move on to the nest test
+latency_runtime=60
 search_runtime=60
 validation_runtime=120
 servers=127.0.0.1
@@ -72,7 +73,11 @@ if [ $? -ne 0 ]; then
 	printf -- "\t\t-c str       --config=str               name of the test config (i.e. jumbo_frames_and_network_throughput)\n"
 	printf -- "\t\t-r float     --rate[s]	               list of rates in millions of packets/sec (multiple rates can be used for latency tests)\n"
 	printf -- "\t\t             --portlist=int,int[,int,int]  list of DPDK ports to use (multiples of 2)\n"
-	printf -- "\t\t-t str[,str] --test-type=str            throughput or latency (default $test_type)\n"
+	printf -- "\t\t-t str[,str] --test-type=str            throughput, latency, or throughput-latency (default $test_type)\n"
+	printf -- "\t\t					       throuhgput: find max throuhgput with a binary search\n"
+	printf -- "\t\t					       latency: find latency (histogram) at a specified packet rate\n"
+	printf -- "\t\t					       throughput-latency: first find max throuhgput with a binary search, then\n"
+	printf -- "\t\t								   find latency (histogram) at the max throughput\n"
 	printf -- "\t\t-t str[,str] --traffic=str[,str]        list of one or more: unidirec or bidirec (default $traffic)\n"
 	printf -- "\t\t-r int       --latency-runtime=int      test measurement period in seconds when running a latency test (default is $latency_runtime)\n"
 	printf -- "\t\t-r int       --search-runtime=int       test measurement period in seconds when searching for max throughput (default is $search_runtime)\n"
@@ -281,116 +286,123 @@ mkdir -p $benchmark_run_dir/.running
 export benchmark_name config
 pbench-collect-sysinfo --group=$tool_group --dir=$benchmark_run_dir beg
 # start the server processes
-if [ "$test_type" == "latency" -a -z "$rates" ]; then
-	rates=0.1
+if [ -z "$rates" ]; then
+	if [ "$test_type" == "latency" ]; then
+		# use a very low default rate for latency test if none is specified
+		rates=0.1
+	else
+		# a rate of "none" is valid if this is a throuhgput test.  The opnfv-vsperf.lua
+		# script will start with line-rate for the binary search
+		rates="none"
+	fi
 fi
 for rate in `echo $rates | sed -e s/,/" "/g`; do
-for traffic_direction in `echo $traffic | sed -e s/,/" "/g`; do
-	for max_drop_pct in `echo $max_drop_pcts | sed -e s/,/" "/g`; do
-		for frame_size in `echo $frame_sizes | sed -e s/,/" "/g`; do
-			for nr_flow in `echo $nr_flows | sed -e s/,/" "/g`; do
-				if [ $count -ge $start_iteration_num ]; then
-					if [ "$test_type" == "latency" ]; then
-						iteration="${count}-${test_type}-${traffic_direction}=${frame_size}B-${nr_flow}flows-${rate}Mpps"
-					else 
-						iteration="${count}-${test_type}-${traffic_direction}=${frame_size}B-${nr_flow}flows-${max_drop_pct}pct_drop"
-					fi
-					iteration_dir="$benchmark_run_dir/$iteration"
-					result_stddevpct=$maxstddevpct # this test case will get a "do-over" if the stddev is not low enough
-					failures=0
-					echo "Starting iteration[$iteration] ($count of $total_iterations)"
-					log "Starting iteration[$iteration] ($count of $total_iterations)"
-					while [[ $(echo "if (${result_stddevpct} >= ${maxstddevpct}) 1 else 0" | bc) -eq 1 ]]; do
-						if [[ $failures -gt 0 ]]; then
-							echo "Restarting iteration[$iteration] ($count of $total_iterations)"
-							log "Restarting iteration[$iteration] ($count of $total_iterations)"
+	for traffic_direction in `echo $traffic | sed -e s/,/" "/g`; do
+		for max_drop_pct in `echo $max_drop_pcts | sed -e s/,/" "/g`; do
+			for frame_size in `echo $frame_sizes | sed -e s/,/" "/g`; do
+				for nr_flow in `echo $nr_flows | sed -e s/,/" "/g`; do
+					if [ $count -ge $start_iteration_num ]; then
+						if [ "$test_type" == "latency" ]; then
+							iteration="${count}-${test_type}-${traffic_direction}=${frame_size}B-${nr_flow}flows-${rate}Mpps"
+						else 
+							iteration="${count}-${test_type}-${traffic_direction}=${frame_size}B-${nr_flow}flows-${max_drop_pct}pct_drop"
 						fi
-						mkdir -p $iteration_dir
-						if [ "$postprocess_only" != "y" ]; then
-							pushd >/dev/null $moongen_dir
-							if [ $traffic_direction == "unidirec" ]; then
-								bidirec_opt=false
-							else
-								bidirec_opt=true
+						iteration_dir="$benchmark_run_dir/$iteration"
+						result_stddevpct=$maxstddevpct # this test case will get a "do-over" if the stddev is not low enough
+						failures=0
+						echo "Starting iteration[$iteration] ($count of $total_iterations)"
+						log "Starting iteration[$iteration] ($count of $total_iterations)"
+						while [[ $(echo "if (${result_stddevpct} >= ${maxstddevpct}) 1 else 0" | bc) -eq 1 ]]; do
+							if [[ $failures -gt 0 ]]; then
+								echo "Restarting iteration[$iteration] ($count of $total_iterations)"
+								log "Restarting iteration[$iteration] ($count of $total_iterations)"
 							fi
-							echo "VSPERF {" >$cfg_file
-							if [ ! -z "$rate" ]; then
-        							echo "startRate = $rate," >>$cfg_file
-							fi
-        						echo "nrFlows = $nr_flow," >>$cfg_file
-        						echo "testType = \"$test_type\"," >>$cfg_file
-        						echo "runBidirec = $bidirec_opt," >>$cfg_file
-							if [ "$test_type" == "latency" ]; then
-								echo "latencyRunTime = $latency_runtime,">>$cfg_file
-							else
-        							echo "searchRunTime = $search_runtime,">>$cfg_file
-        							echo "validationRunTime = $validation_runtime,">> $cfg_file
-        							echo "acceptableLossPct = $max_drop_pct," >>$cfg_file
-							fi
-        						echo "frameSize = $frame_size,">>$cfg_file
-        						echo "ports = {$portlist}" >>$cfg_file
-							echo "}">>$cfg_file
-							cp $cfg_file $iteration_dir/$cfg_file
-							popd >/dev/null
-						fi
-						# each attempt at a test config requires multiple samples to get stddev
-						for sample in `seq 1 $nr_samples`; do
-							benchmark_results_dir="$iteration_dir/sample$sample"
+							mkdir -p $iteration_dir
 							if [ "$postprocess_only" != "y" ]; then
 								pushd >/dev/null $moongen_dir
-								mkdir -p $benchmark_results_dir
-								echo "test sample $sample of $nr_samples"
-								log "test sample $sample of $nr_samples "
-								benchmark_client_cmd_file="$iteration_dir/$benchmark_name-client.cmd"
-								result_file=$benchmark_results_dir/moongen-result.txt
-								# save benchmark command in file for debugging or running manually
-								
-
-								echo "pushd >/dev/null $moongen_dir" >$benchmark_client_cmd_file
-								echo "./build/MoonGen ./examples/opnfv-vsperf.lua" >>$benchmark_client_cmd_file
-								echo "popd >/dev/null $moongen_dir" >>$benchmark_client_cmd_file
-								chmod +x $benchmark_client_cmd_file
-								pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-								$benchmark_client_cmd_file | tee $result_file
-								pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-								pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
-								/bin/cp $moongen_dir/hist.csv $benchmark_results_dir
-								popd >/dev/null
-							else
-								if [[ ! -d $benchmark_results_dir ]]; then
-									error_log "Results directory $benchmark_results_dir does not exist, skipping post-processing"
-									continue
+								if [ $traffic_direction == "unidirec" ]; then
+									bidirec_opt=false
+								else
+									bidirec_opt=true
 								fi
-								echo "Not going to run $benchmark_name.  Only postprocesing existing data"
-								log "Not going to run $benchmnark_name.  Only postprocesing existing data"
+								echo "VSPERF {" >$cfg_file
+								if [ "$rate" != "none" ]; then
+        								echo "startRate = $rate," >>$cfg_file
+								fi
+        							echo "nrFlows = $nr_flow," >>$cfg_file
+        							echo "testType = \"$test_type\"," >>$cfg_file
+        							echo "runBidirec = $bidirec_opt," >>$cfg_file
+								if [ "$test_type" == "latency" ]; then
+									echo "latencyRunTime = $latency_runtime,">>$cfg_file
+								else
+        								echo "searchRunTime = $search_runtime,">>$cfg_file
+        								echo "validationRunTime = $validation_runtime,">> $cfg_file
+        								echo "acceptableLossPct = $max_drop_pct," >>$cfg_file
+								fi
+        							echo "frameSize = $frame_size,">>$cfg_file
+        							echo "ports = {$portlist}" >>$cfg_file
+								echo "}">>$cfg_file
+								cp $cfg_file $iteration_dir/$cfg_file
+								popd >/dev/null
 							fi
-							echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $test_type $tool_label_pattern $tool_group" >"$benchmark_results_dir/moongen-postprocess.cmd"
-							$script_path/postprocess/$benchmark_name-postprocess "$benchmark_results_dir" "$iteration" "$test_type" "$tool_label_pattern" "$tool_group"
-						done
-						echo "$script_path/postprocess/process-iteration-samples $iteration_dir Mframes_sec $maxstddevpct $failures $max_failures $tar_nonref_data $keep_failed_tool_data" >"$iteration_dir/process-iteration-samples.cmd"
-						$script_path/postprocess/process-iteration-samples "$iteration_dir" "Mframes_sec" "$maxstddevpct" "$failures" "$max_failures" "$tar_nonref_data" "$keep_failed_tool_data"
-						fail=$?
-						if [ $fail -eq 1 ]; then
-							error_log "This test iteration failed"
-							((failures++))
-						fi
-						if [ $fail -eq 0 -o $failures -ge $max_failures ]; then
-							debug_log "Moving to the next iteration"
-							break
-						fi
-					done # break out of this loop only if the $result_stddevpct is lower than $maxstddevpct
-					echo "Iteration $iteration complete ($count of $total_iterations), with 1 pass and $failures failures"
-					log "Iteration $iteration complete ($count of $total_iterations), with 1 pass and $failures failures"
-				else
-					echo "Skipping iteration $iteration ($count of $total_iterations)"
-					log "Skipping iteration $iteration ($count of $total_iterations)"
-				fi
-				last_test_type="$test_type"
-				let count=$count+1 # now we can move to the next iteration
+							# each attempt at a test config requires multiple samples to get stddev
+							for sample in `seq 1 $nr_samples`; do
+								benchmark_results_dir="$iteration_dir/sample$sample"
+								if [ "$postprocess_only" != "y" ]; then
+									pushd >/dev/null $moongen_dir
+									mkdir -p $benchmark_results_dir
+									echo "test sample $sample of $nr_samples"
+									log "test sample $sample of $nr_samples "
+									benchmark_client_cmd_file="$iteration_dir/$benchmark_name-client.cmd"
+									result_file=$benchmark_results_dir/moongen-result.txt
+									# save benchmark command in file for debugging or running manually
+									
+	
+									echo "pushd >/dev/null $moongen_dir" >$benchmark_client_cmd_file
+									echo "./build/MoonGen ./examples/opnfv-vsperf.lua" >>$benchmark_client_cmd_file
+									echo "popd >/dev/null $moongen_dir" >>$benchmark_client_cmd_file
+									chmod +x $benchmark_client_cmd_file
+									pbench-start-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									$benchmark_client_cmd_file | tee $result_file
+									pbench-stop-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									pbench-postprocess-tools --group=$tool_group --iteration=$iteration --dir=$benchmark_results_dir
+									/bin/cp $moongen_dir/hist.csv $benchmark_results_dir
+									popd >/dev/null
+								else
+									if [[ ! -d $benchmark_results_dir ]]; then
+										error_log "Results directory $benchmark_results_dir does not exist, skipping post-processing"
+										continue
+									fi
+									echo "Not going to run $benchmark_name.  Only postprocesing existing data"
+									log "Not going to run $benchmnark_name.  Only postprocesing existing data"
+								fi
+								echo "$script_path/postprocess/$benchmark_name-postprocess $benchmark_results_dir $iteration $test_type $tool_label_pattern $tool_group" >"$benchmark_results_dir/moongen-postprocess.cmd"
+								$script_path/postprocess/$benchmark_name-postprocess "$benchmark_results_dir" "$iteration" "$test_type" "$tool_label_pattern" "$tool_group"
+							done
+							echo "$script_path/postprocess/process-iteration-samples $iteration_dir Mframes_sec $maxstddevpct $failures $max_failures $tar_nonref_data $keep_failed_tool_data" >"$iteration_dir/process-iteration-samples.cmd"
+							$script_path/postprocess/process-iteration-samples "$iteration_dir" "Mframes_sec" "$maxstddevpct" "$failures" "$max_failures" "$tar_nonref_data" "$keep_failed_tool_data"
+							fail=$?
+							if [ $fail -eq 1 ]; then
+								error_log "This test iteration failed"
+								((failures++))
+							fi
+							if [ $fail -eq 0 -o $failures -ge $max_failures ]; then
+								debug_log "Moving to the next iteration"
+								break
+							fi
+						done # break out of this loop only if the $result_stddevpct is lower than $maxstddevpct
+						echo "Iteration $iteration complete ($count of $total_iterations), with 1 pass and $failures failures"
+						log "Iteration $iteration complete ($count of $total_iterations), with 1 pass and $failures failures"
+					else
+						echo "Skipping iteration $iteration ($count of $total_iterations)"
+						log "Skipping iteration $iteration ($count of $total_iterations)"
+					fi
+					last_test_type="$test_type"
+					let count=$count+1 # now we can move to the next iteration
+				done
 			done
 		done
 	done
-done
 done
 echo "$script_path/postprocess/generate-benchmark-summary $benchmark_name $orig_cmd $benchmark_run_dir" >"$benchmark_run_dir/generate-benchmark-summary.cmd"
 $script_path/postprocess/generate-benchmark-summary "$benchmark_name" "$orig_cmd" "$benchmark_run_dir"
